"""
Pre-cached audio cue registry for the TeachingAgent.

These cues are the ONLY hardcoded spoken strings for the teaching flow.
All other speech is generated by the LLM. Register them with the
AudioCueService at agent startup so they are available for instant playback.
"""

# Cue key -> spoken text for pre-cached TTS audio.
SQUAT_TEACHING_CUES = {
    # Fired during active movement only
    "knees_out": "Knees out.",
    "chest_up": "Chest up.",
    "up": "Up!",

    # Fired at rep completion (clean rep only) — one chosen randomly per rep
    "good": "Good.",
    "nice": "Nice.",
    "clean": "Clean.",
    "yeah": "Yeah.",
}

# Keys eligible for random selection on a clean rep completion.
CLEAN_REP_CUE_KEYS = ["good", "nice", "clean", "yeah"]
